[versions]
springBoot = "3.3.4"
springFramework = "6.1.13"
slf4j = "2.0.16"
freemarker = "2.3.33"
testcontainers = "1.20.1"
wiremock = "3.9.1"
archunit = "1.3.0"
httpclient5 = "5.3.1"
postgres = "42.7.4"
flyway = "10.17.3"
lombok = "1.18.34"
springSecurityCrypto = "6.3.3"
javaJwt = "4.4.0"
springdoc = "2.6.0"
swagger = "2.2.22"
flyingSaucer = "9.13.0"
zxing = "3.5.3"
awsSdk = "2.28.11"
caffeine = "3.1.8"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springBoot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springBoot" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc", version.ref = "springBoot" }
spring-boot-starter-json = { module = "org.springframework.boot:spring-boot-starter-json", version.ref = "springBoot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "springBoot" }
spring-tx = { module = "org.springframework:spring-tx", version.ref = "springFramework" }
spring-context = { module = "org.springframework:spring-context", version.ref = "springFramework" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }
flying-saucer-pdf = { module = "org.xhtmlrenderer:flying-saucer-pdf", version.ref = "flyingSaucer" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }
zxing-javase = { module = "com.google.zxing:javase", version.ref = "zxing" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
testcontainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-minio = { module = "org.testcontainers:minio", version.ref = "testcontainers" }
aws-s3 = { module = "software.amazon.awssdk:s3", version.ref = "awsSdk" }
aws-url-connection-client = { module = "software.amazon.awssdk:url-connection-client", version.ref = "awsSdk" }
wiremock = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }
archunit = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
httpclient5 = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "httpclient5" }
junit-bom = { module = "org.junit:junit-bom", version = "5.10.3" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
assertj = { module = "org.assertj:assertj-core", version = "3.26.3" }
mockito = { module = "org.mockito:mockito-core", version = "5.12.0" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

spring-security-crypto = { module = "org.springframework.security:spring-security-crypto", version.ref = "springSecurityCrypto" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "javaJwt" }
spring-boot-starter-mail = { module = "org.springframework.boot:spring-boot-starter-mail", version.ref = "springBoot" }
springdoc-openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations-jakarta", version.ref = "swagger" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.6" }
